wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.5.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.30
      6: 4.5.0
      8:
      - 5
learning_rate:
  desc: null
  value: 0.00680939417285755
num_train_epochs:
  desc: null
  value: 6
per_device_train_batch_size:
  desc: null
  value: 4
